[ADD] Bibliografia, filminas y algunas soluciones
FAMAF-resources/2_2C-Introduccion_a_la_Logica_y_la_computacion-FAMAF pull request #1
Opened 2023-07-27 11:13 UTC by diofanto33

2023-07-27 15:27 UTC, shirosweets requested changes
Podrias agregar las filminas dentro de una carpeta "teorico/2021"?

2023-07-27 17:24 UTC, diofanto33 commented
Ya hice el commit, creo que la pull request se actualiza automaticamente, puede ser?

2023-07-27 18:57 UTC, AgustinMDominguez approved these changes
Excelente la cantidad y completitud de estos apuntes 👍🏻

2023-07-28 03:10 UTC, shirosweets approved these changes

2023-07-28 03:10 UTC, merged